// The pieces shown on the website.
//
// Each entry links to an item in Grace's Square catalog by its code (C236, R4 ...).
// Square stays the source of truth for PRICE and whether a piece is still AVAILABLE:
// the site reads both from Square (see lib/square.ts). Everything else here
// (website title, story, size) is what visitors see. Square keeps the short codes
// so Grace can find pieces fast at the booth.
//
// The price and available values below are only a fallback for when Square
// can't be reached.
//
// To add a piece: copy an entry, give it a website title and slug, put the
// Square code and IDs in, and save a photo as /public/art/<slug>.jpg as a backup.

export type Format = "canvas" | "card";
export type Wall = "terracotta" | "pink" | "teal" | "mustard" | "sky" | "orange" | "paper";

export type Artwork = {
  slug: string;
  title: string;
  price: number; // US dollars
  available: boolean; // false = already collected
  format: Format;
  size: string;
  medium: string;
  series?: string;
  story: string[]; // paragraphs, in Grace's words
  details?: string[];
  image: string;
  // Squarespace URL this piece used to live at, so old links keep working
  oldPath?: string;
  // Color of the "wall" the piece hangs on across the site. Pick one that sits
  // well with the painting. Options: terracotta, pink, teal, mustard, sky, orange, paper.
  wall?: Wall;
  // true = use the photo in /public/art instead of the Square photo.
  localPhoto?: boolean;
  // Link to Square. Leave out for pieces that only ever sold on Squarespace.
  square?: { code: string; itemId: string; variationId: string };
};

export const artworks: Artwork[] = [
  {
    slug: "built-in-bloom",
    wall: "mustard",
    title: "Built in Bloom",
    price: 400,
    square: { code: "R4", itemId: "MKRYX4DVPALOJIJ4N4XACUJU", variationId: "ZXLQDWQMEGL7QYIYBM5Q56AZ" },
    available: true,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "This portrait is fully layered in hand-painted florals, with every inch of the silhouette filled with color and detail. Outlined in yellow and set against a muted terracotta background, the figure feels grounded yet vibrant.",
      "Built in Bloom is about becoming who you are through everything you've grown through, and standing confidently in that truth.",
    ],
    image: "/art/built-in-bloom.jpg",
    oldPath: "/store/p/floral-crown",
  },
  {
    slug: "rooted-in-radiance",
    wall: "teal",
    title: "Rooted in Radiance",
    price: 250,
    square: { code: "S5", itemId: "ZRRBWOUYABT4RK7YJTUOGHJH", variationId: "DP7LWCFBSLDTDO63PLCAIUND" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "A striking portrait of quiet strength and blooming self-love, Rooted in Radiance features a faceless figure crowned and cloaked in brilliant florals. Her smooth, bald head glows against a soft pink background, letting every color bloom brighter. Gold accents in her jewelry add a regal touch, honoring her dignity and depth.",
      "This piece is a reminder that beauty doesn't need permission. It blossoms from within.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/rooted-in-radiance.jpg",
    oldPath: "/store/p/rooted-in-radiance",
  },
  {
    slug: "in-full-bloom",
    wall: "sky",
    title: "In Full Bloom",
    price: 250,
    square: { code: "S6", itemId: "6Y4F5RHKXBB5VHCJLIJRQJCJ", variationId: "VEZ2UP47K7747AQWEV3QTHXW" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "With a backdrop of playful pink and white stripes, In Full Bloom is a joyful tribute to individuality. Bursting with colorful blossoms and crowned with confidence, this faceless figure invites viewers to see themselves in her. The contrast between the bright floral palette and her bold red lips makes this piece both soft and striking.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/in-full-bloom.jpg",
    oldPath: "/store/p/in-full-bloom",
  },
  {
    slug: "crowned-in-confidence",
    wall: "pink",
    title: "Crowned in Confidence",
    price: 250,
    square: { code: "S2", itemId: "TF7I2BC2QUDRK2AF6QYB4GBM", variationId: "K6FBBOTBSTJQK6HEL6GCJLMM" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    story: [
      "With her head held high and adorned with delicate hair ties and a golden crown, Crowned in Confidence honors the quiet strength and bold beauty of Black girlhood. Her eyes speak volumes: resilient, soft, and self-assured. Vibrant orange and red florals bloom around her like an offering of grace.",
      "Set against a rich teal background, this piece invites viewers to remember the power of presence and the importance of being seen.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/crowned-in-confidence.jpg",
    oldPath: "/store/p/crowned-in-confidence",
  },
  // Hand-painted cards. Website titles here; Square keeps the C codes.
  // Photos are Grace's own (localPhoto: true), so they are used instead of the Square photo.
  {
    slug: "covered-in-color",
    wall: "sky",
    title: "Covered in Color",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A faceless figure with flowers growing over her head and shoulders, set against bright yellow and white. Red blooms reach in from the top corner."],
    image: "/art/covered-in-color.jpg",
    localPhoto: true,
    square: { code: "C236", itemId: "CVWKFWVGOBNDLDLD6O6OR26C", variationId: "CTHJG5BLH5VO3YUOUUMBQGAM" },
  },
  {
    slug: "blue-hair-day",
    wall: "mustard",
    title: "Blue Hair Day",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A face drawn in quick, loose lines, with spiky blue hair and red lips, over a wash of watercolor splashes."],
    image: "/art/blue-hair-day.jpg",
    localPhoto: true,
    square: { code: "C124", itemId: "VQ43MSQ7GXYUPDOLYEZZ2GWT", variationId: "G3ZMNHURETOAFNNXAHE35LPM" },
  },
  {
    slug: "garden-face",
    wall: "pink",
    title: "Garden Face",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A face hidden in a field of flowers. Look for the eyes and lips among the stems and petals."],
    image: "/art/garden-face.jpg",
    localPhoto: true,
    square: { code: "C126", itemId: "GH7D3QPGQFQJ4UK6SORZ4MSC", variationId: "WC55EWYRO5VL65CYLM4LA7BX" },
  },
  {
    slug: "white-line",
    wall: "pink",
    title: "White Line",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A portrait drawn in a single white line on black, with a swirling pattern across the shoulders."],
    image: "/art/white-line.jpg",
    localPhoto: true,
    square: { code: "C177", itemId: "M7WS4RMMQDY2T52GU2BOTPCM", variationId: "SV7APAF3CQUCGCWKN6YQH3J4" },
  },
  {
    slug: "orange-cap",
    wall: "teal",
    title: "Orange Cap",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A girl in an orange cap and orange top, holding a green plant, against a layered collage background."],
    image: "/art/orange-cap.jpg",
    localPhoto: true,
    square: { code: "C216", itemId: "5AYDCYVCP3ZUXSPWAD3WAML2", variationId: "TYKD52D3D7NZ7QGDDEWGYELU" },
  },
  {
    slug: "pink-palm",
    wall: "sky",
    title: "Pink Palm",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A tall plant with purple and pink leaves, painted over a soft peach background."],
    image: "/art/pink-palm.jpg",
    localPhoto: true,
    square: { code: "C260", itemId: "5SK43FT5VHKV2QWTPQWLDDDN", variationId: "RW3EIUUW3XFSTVUC62VWNNGC" },
  },
  {
    slug: "hidden-garden",
    wall: "terracotta",
    title: "Hidden Garden",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["Layers of flowers and leaves in yellow, pink and purple, with a face that shows up the longer you look."],
    image: "/art/hidden-garden.jpg",
    localPhoto: true,
    square: { code: "C261", itemId: "VNKZEAWILUA6NJE47RWOEV5M", variationId: "MWNXYDCSTSZEHAFPHV7EYPSH" },
  },
  {
    slug: "blue-hair-and-a-bee",
    wall: "mustard",
    title: "Blue Hair and a Bee",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A faceless figure with bright blue hair and a small bouquet, with a bee visiting from the side."],
    image: "/art/blue-hair-and-a-bee.jpg",
    localPhoto: true,
    square: { code: "C86", itemId: "KVHKFIO3ECXKH6PPA7RN6PLY", variationId: "F7LPL4C6EAX2OA3FCGEWDY5Y" },
  },
  {
    slug: "hoop-earrings",
    wall: "orange",
    title: "Hoop Earrings",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A white line portrait on black, with big hoop earrings and a swirling pattern across the shoulders."],
    image: "/art/hoop-earrings.jpg",
    localPhoto: true,
    square: { code: "C172", itemId: "YTBOLBHTWC2QNRG2FOHJP7LL", variationId: "OBR4WUSJZOZZU7J3VKZZS7X2" },
  },
  {
    slug: "wings",
    wall: "mustard",
    title: "Wings",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A black silhouette with sweeping shapes like folded wings, over blue and orange watercolor."],
    image: "/art/wings.jpg",
    localPhoto: true,
    square: { code: "C184", itemId: "WDMOIXOTL42WDLGV5OMW2NHF", variationId: "PWX4RVG3S7C6ZCTFGM4MU34J" },
  },
  {
    slug: "curls-and-color",
    wall: "teal",
    title: "Curls and Color",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman with a full crown of curls, surrounded by bold strokes of red, blue and yellow."],
    image: "/art/curls-and-color.jpg",
    localPhoto: true,
    square: { code: "C185", itemId: "QR7SRCWKNDGCDNHBSIS6QKZS", variationId: "WKJ6GDM4X7MMC5UOQ4U7G53O" },
  },
  {
    slug: "orange-blossoms",
    wall: "sky",
    title: "Orange Blossoms",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A girl with orange flowers in her hair and a small bouquet, against a busy collage background."],
    image: "/art/orange-blossoms.jpg",
    localPhoto: true,
    square: { code: "C215", itemId: "Z2L7DIXWKI5EZXB3MIYW3HBW", variationId: "PUSBYKSM4QMITAUKDUKJMFZD" },
  },
  {
    slug: "covered-in-color-ii",
    wall: "pink",
    title: "Covered in Color II",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A second take on Covered in Color: a faceless figure filled with flowers, against yellow and white."],
    image: "/art/covered-in-color-ii.jpg",
    localPhoto: true,
    square: { code: "C237", itemId: "TPQY7BE7EQXXKWHNA5EQIN56", variationId: "MNYSXUKMDAKNZFU6ODGGHVNK" },
  },
  {
    slug: "green-hair",
    wall: "mustard",
    title: "Green Hair",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A faceless figure with green hair on a coral background, with coral-colored branches and flowers at the shoulder."],
    image: "/art/green-hair.jpg",
    localPhoto: true,
    square: { code: "C239", itemId: "4GIW6H53SZNTXNFJHDAXSZTY", variationId: "K5TW2IOR5VNBXPVTMYMQ7I6M" },
  },
  {
    slug: "purple-hair",
    wall: "teal",
    title: "Purple Hair",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A faceless figure with purple hair on gold, her top covered in small yellow flowers and leaves."],
    image: "/art/purple-hair.jpg",
    localPhoto: true,
    square: { code: "C238", itemId: "GADQSSHJJ5H4IWWNEUYHRUX7", variationId: "UWSEYVUPVCKNYMAKMS6G76PL" },
  },
  {
    slug: "white-vase",
    wall: "sky",
    title: "White Vase",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["Pink and green stems spilling out of a white vase, over yellow and soft white."],
    image: "/art/white-vase.jpg",
    localPhoto: true,
    square: { code: "C259", itemId: "QBJOQ5VZDNXKO5ZUU7D4DBS2", variationId: "BWDZOMCECWPFBHF6TGINQWHI" },
  },
  {
    slug: "wild-garden",
    wall: "terracotta",
    title: "Wild Garden",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A dense tangle of flowers in yellow, purple and white, layered until the background disappears."],
    image: "/art/wild-garden.jpg",
    localPhoto: true,
    square: { code: "C262", itemId: "JXG3EBT6UC73EQCEA7Y3NLPH", variationId: "EYLVN5VF6LRSXNYWDELTW6A4" },
  },
  {
    slug: "flourish",
    wall: "mustard",
    title: "Flourish",
    price: 250,
    square: { code: "S4", itemId: "4R4NB3MAMTR62K7NRVFZWMH7", variationId: "MVWTXZJAT6L6QVS5YD3RJB3L" },
    available: false,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "A bold celebration of Black beauty and blooming identity, Flourish features a faceless silhouette adorned with vibrant hand-painted florals. Each petal is an expression of joy, each leaf a whisper of growth. Set against a calming sky-blue background, this piece evokes both peace and power.",
      "Flourish reminds us that home is where we grow into ourselves.",
    ],
    image: "/art/flourish.jpg",
    oldPath: "/store/p/flourish",
  },
  {
    slug: "its-my-time",
    wall: "teal",
    title: "It's My Time",
    price: 400,
    square: { code: "R1", itemId: "PX4GZOJTCEKOPA64P352F5SS", variationId: "63Z4RZZJ4SUTHUYV2ILWYJ6S" },
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "Floral patterns crown this faceless figure, with gold earrings and a necklace adding a subtle sense of elegance. Set against a rich pink background, It's My Time is about strength, softness, and growing into your full self.",
    ],
    image: "/art/its-my-time.jpg",
    oldPath: "/store/p/built-in-bloom",
  },
  {
    slug: "surviving-corporate-america",
    wall: "sky",
    title: "Surviving Corporate America",
    price: 200,
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    story: [
      "A bright yellow backdrop makes this portrait glow. Swirls of teal, orange, and purple move across the figure's face and chest, adding energy and rhythm to the piece.",
    ],
    image: "/art/surviving-corporate-america.jpg",
    oldPath: "/store/p/be-the-light",
  },
  {
    slug: "fully-seen",
    wall: "teal",
    title: "Fully Seen",
    price: 400,
    square: { code: "R2", itemId: "QQ6ADGLYEJLS5OCTIGBLYTPN", variationId: "OICSMFLXTF6RZNLOQMHBXFLB" },
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    story: [
      "A faceless Black figure with long painted lashes, bold red lips, and a single flower over the heart, set against a bright orange background. Fully Seen is about presence. It's a reminder that you don't need to explain yourself to be powerful. You just need to show up.",
    ],
    image: "/art/fully-seen.jpg",
    oldPath: "/store/p/fully-seen",
  },
  {
    slug: "bright-and-grounded",
    wall: "pink",
    title: "Bright and Grounded",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A faceless figure in front of a vibrant, abstract background. Delicate blue and orange flowers grow from the chest. This piece blends boldness with calm, and is meant to bring color and care into small moments.",
    ],
    image: "/art/bright-and-grounded.jpg",
    oldPath: "/store/p/76watsn2q4p3lggyn1vz725kp1scuy",
  },
  {
    slug: "every-side-of-me",
    wall: "mustard",
    title: "Every Side of Me",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A colorful face split into bold shapes and sections. This card is about embracing every part of yourself: the loud, the quiet, the serious, the playful.",
    ],
    image: "/art/every-side-of-me.jpg",
    oldPath: "/store/p/every-side-of-me",
  },
  {
    slug: "layered-beauty",
    wall: "terracotta",
    title: "Layered Beauty",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A floral-covered silhouette set against a layered, textured background. Made for anyone who finds power in their softness.",
    ],
    image: "/art/layered-beauty.jpg",
    oldPath: "/store/p/layered-beauty",
  },
  {
    slug: "family-unit",
    wall: "sky",
    title: "Family Unit",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Watercolor on paper",
    story: [
      "A minimalist portrait of three faceless figures side by side. The simple shapes and soft tones reflect closeness, love, and identity within a family.",
    ],
    image: "/art/family-unit.jpg",
    oldPath: "/store/p/family-unit",
  },
];

export const available = () => artworks.filter((a) => a.available);
export const collected = () => artworks.filter((a) => !a.available);
export const bySlug = (slug: string) => artworks.find((a) => a.slug === slug);

export const formatPrice = (n: number) =>
  `$${n.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
