// The pieces shown on the website.
//
// Each entry links to an item in Grace's Square catalog by its code (C236, R4 ...).
// Square stays the source of truth for PRICE and whether a piece is still AVAILABLE:
// the site reads both from Square (see lib/square.ts). Everything else here
// (website title, story, size) is what visitors see. Square keeps the short codes
// so Grace can find pieces fast at the booth.
//
// The price and available values below are only a fallback for when Square
// can't be reached.
//
// To add a piece: copy an entry, give it a website title and slug, put the
// Square code and IDs in, and save a photo as /public/art/<slug>.jpg as a backup.

export type Format = "canvas" | "card";
export type Wall = "terracotta" | "pink" | "teal" | "mustard" | "sky" | "orange" | "paper";

export type Artwork = {
  slug: string;
  title: string;
  price: number; // US dollars
  available: boolean; // false = already collected
  format: Format;
  size: string;
  medium: string;
  series?: string;
  story: string[]; // paragraphs, in Grace's words
  details?: string[];
  image: string;
  // Squarespace URL this piece used to live at, so old links keep working
  oldPath?: string;
  // Color of the "wall" the piece hangs on across the site. Pick one that sits
  // well with the painting. Options: terracotta, pink, teal, mustard, sky, orange, paper.
  wall?: Wall;
  // Link to Square. Leave out for pieces that only ever sold on Squarespace.
  square?: { code: string; itemId: string; variationId: string };
};

export const artworks: Artwork[] = [
  {
    slug: "built-in-bloom",
    wall: "mustard",
    title: "Built in Bloom",
    price: 400,
    square: { code: "R4", itemId: "MKRYX4DVPALOJIJ4N4XACUJU", variationId: "ZXLQDWQMEGL7QYIYBM5Q56AZ" },
    available: true,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "This portrait is fully layered in hand-painted florals, with every inch of the silhouette filled with color and detail. Outlined in yellow and set against a muted terracotta background, the figure feels grounded yet vibrant.",
      "Built in Bloom is about becoming who you are through everything you've grown through, and standing confidently in that truth.",
    ],
    image: "/art/built-in-bloom.jpg",
    oldPath: "/store/p/floral-crown",
  },
  {
    slug: "rooted-in-radiance",
    wall: "teal",
    title: "Rooted in Radiance",
    price: 250,
    square: { code: "S5", itemId: "ZRRBWOUYABT4RK7YJTUOGHJH", variationId: "DP7LWCFBSLDTDO63PLCAIUND" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "A striking portrait of quiet strength and blooming self-love, Rooted in Radiance features a faceless figure crowned and cloaked in brilliant florals. Her smooth, bald head glows against a soft pink background, letting every color bloom brighter. Gold accents in her jewelry add a regal touch, honoring her dignity and depth.",
      "This piece is a reminder that beauty doesn't need permission. It blossoms from within.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/rooted-in-radiance.jpg",
    oldPath: "/store/p/rooted-in-radiance",
  },
  {
    slug: "in-full-bloom",
    wall: "sky",
    title: "In Full Bloom",
    price: 250,
    square: { code: "S6", itemId: "6Y4F5RHKXBB5VHCJLIJRQJCJ", variationId: "VEZ2UP47K7747AQWEV3QTHXW" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "With a backdrop of playful pink and white stripes, In Full Bloom is a joyful tribute to individuality. Bursting with colorful blossoms and crowned with confidence, this faceless figure invites viewers to see themselves in her. The contrast between the bright floral palette and her bold red lips makes this piece both soft and striking.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/in-full-bloom.jpg",
    oldPath: "/store/p/in-full-bloom",
  },
  {
    slug: "crowned-in-confidence",
    wall: "pink",
    title: "Crowned in Confidence",
    price: 250,
    square: { code: "S2", itemId: "TF7I2BC2QUDRK2AF6QYB4GBM", variationId: "K6FBBOTBSTJQK6HEL6GCJLMM" },
    available: true,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    story: [
      "With her head held high and adorned with delicate hair ties and a golden crown, Crowned in Confidence honors the quiet strength and bold beauty of Black girlhood. Her eyes speak volumes: resilient, soft, and self-assured. Vibrant orange and red florals bloom around her like an offering of grace.",
      "Set against a rich teal background, this piece invites viewers to remember the power of presence and the importance of being seen.",
    ],
    details: ["Ready to hang", "One-of-a-kind original"],
    image: "/art/crowned-in-confidence.jpg",
    oldPath: "/store/p/crowned-in-confidence",
  },
  // Hand-painted cards. Website titles here; Square keeps the C codes.
  {
    slug: "covered-in-color",
    wall: "sky",
    title: "Covered in Color",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A faceless figure with flowers growing over her head and shoulders, set against bright yellow and white. Red blooms reach in from the top corner."],
    image: "/art/covered-in-color.jpg",
    square: { code: "C236", itemId: "CVWKFWVGOBNDLDLD6O6OR26C", variationId: "CTHJG5BLH5VO3YUOUUMBQGAM" },
  },
  {
    slug: "halo",
    wall: "terracotta",
    title: "Halo",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman with long braids and a thin silver halo. Her blue dress is filled with wildflowers and berry branches, on a warm yellow background."],
    image: "/art/halo.jpg",
    square: { code: "C207", itemId: "GVU3VXXXFDI4ECPSXOKQMRES", variationId: "4OHP22EUADKMHL2EOZ3QRGYC" },
  },
  {
    slug: "one-blue-flower",
    wall: "pink",
    title: "One Blue Flower",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman with a long braid over her shoulder and a single blue flower in her hair, set against gold. A second blue flower sits at her neckline."],
    image: "/art/one-blue-flower.jpg",
    square: { code: "C208", itemId: "MMNN5LPFWCQJL53THNQT2BJK", variationId: "TQESZIFKAY3XCLFS4G3FJ2ZK" },
  },
  {
    slug: "garden-wrap",
    wall: "mustard",
    title: "Garden Wrap",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman in a green headwrap full of leaves and small flowers, against a deep mauve background."],
    image: "/art/garden-wrap.jpg",
    square: { code: "C209", itemId: "MWYOZBSOTPSI6MQACMN4UGFO", variationId: "NEDMCFJOB53JCQMFWN23SM7O" },
  },
  {
    slug: "flower-crown",
    wall: "pink",
    title: "Flower Crown",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman in an orange hat ringed with small flowers, with a matching flower collar, under a clear blue sky."],
    image: "/art/flower-crown.jpg",
    square: { code: "C234", itemId: "ISGN4YS4B7IZ7VDO6LEZEZ4P", variationId: "2QEHZM23NSJO26N77UAG7ZHC" },
  },
  {
    slug: "soft-curls",
    wall: "mustard",
    title: "Soft Curls",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman with full dark curls and silver hoops, in a teal top with a white swirl at the collar, on coral pink."],
    image: "/art/soft-curls.jpg",
    square: { code: "C191", itemId: "262FJBQLT7NP534CJEEGI3BI", variationId: "VPSNASXCXAASHDLEUZWAFGRY" },
  },
  {
    slug: "yellow-bucket-hat",
    wall: "sky",
    title: "Yellow Bucket Hat",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman in a bright yellow bucket hat and a layered silver necklace, on a coral background."],
    image: "/art/yellow-bucket-hat.jpg",
    square: { code: "C192", itemId: "HIONIQVZE5PRXX2PYD7DDSXF", variationId: "37E54P6S45LSF4HPQWSMM2NL" },
  },
  {
    slug: "blue-pattern",
    wall: "orange",
    title: "Blue Pattern",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman with gold earrings and a blue top covered in white squiggles, set against soft gray."],
    image: "/art/blue-pattern.jpg",
    square: { code: "C196", itemId: "TPNQ5OK5FFTUIPMC2LZYQMWF", variationId: "74LGRMHGFHMT6APHTUZHYNPA" },
  },
  {
    slug: "sun-at-her-back",
    wall: "teal",
    title: "Sun at Her Back",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A small figure in a blue dress standing in front of a big orange sun."],
    image: "/art/sun-at-her-back.jpg",
    square: { code: "C136", itemId: "CT4THLG7OFM627W2ZFO5XD4Y", variationId: "FNHLCNM5RLUFPTWY4CI3GW76" },
  },
  {
    slug: "yellow-dress",
    wall: "terracotta",
    title: "Yellow Dress",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A girl in a yellow dress standing in a loose wash of blue, with an orange hanging overhead and pink blooms beside her."],
    image: "/art/yellow-dress.jpg",
    square: { code: "C144", itemId: "DDPCNODVD62PQKQTSAJMECQA", variationId: "5VYFNGXCVIVFB355P26QU4TJ" },
  },
  {
    slug: "pinwheel",
    wall: "mustard",
    title: "Pinwheel",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["Watercolor petals in blue, teal, red and green spinning out from the center like a pinwheel."],
    image: "/art/pinwheel.jpg",
    square: { code: "C14", itemId: "EOO7TUUYOUBGONOCUUB6S2CH", variationId: "SFOSWOOPRLXIUSYPZYHHQAAD" },
  },
  {
    slug: "brown-vase",
    wall: "teal",
    title: "Brown Vase",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A bouquet of red, pink and purple flowers in a round brown vase, on kraft paper with soft white lines."],
    image: "/art/brown-vase.jpg",
    square: { code: "C26", itemId: "AKPQ3GY35NIGWQPNWMTTTYJV", variationId: "OYPM5JLU3SGEZXKTACRN52GN" },
  },
  {
    slug: "wildflower-field",
    wall: "sky",
    title: "Wildflower Field",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A watercolor field of wildflowers in purple, orange and red, with a soft glow of light behind them."],
    image: "/art/wildflower-field.jpg",
    square: { code: "C27", itemId: "TLNWISBX6B5VJVRELPOID5XR", variationId: "QX776ABTDPCCRZ4PPJQTYMGQ" },
  },
  {
    slug: "all-the-pieces",
    wall: "pink",
    title: "All the Pieces",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A face built from blocks of blue, orange and pink, with a green neck and a yellow flower at the shoulder, on gray."],
    image: "/art/all-the-pieces.jpg",
    square: { code: "C175", itemId: "77B2FRW3TMWK64HWR3TEURTF", variationId: "FVJZ776QNTSWUPVAPCPWRE6O" },
  },
  {
    slug: "blue-gown",
    wall: "mustard",
    title: "Blue Gown",
    price: 30,
    available: true,
    format: "card",
    size: "5 x 7 in card",
    medium: "Hand-painted on paper",
    story: ["A woman in a long blue gown standing among tall orange flowers, on dusty pink."],
    image: "/art/blue-gown.jpg",
    square: { code: "C95", itemId: "U25B37QJ7W2K3AJEGMUSL3DJ", variationId: "RWT2UCOTNZUKF7NLOWCLKGTM" },
  },
  {
    slug: "flourish",
    wall: "mustard",
    title: "Flourish",
    price: 250,
    square: { code: "S4", itemId: "4R4NB3MAMTR62K7NRVFZWMH7", variationId: "MVWTXZJAT6L6QVS5YD3RJB3L" },
    available: false,
    format: "canvas",
    size: "12 x 12 in",
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "A bold celebration of Black beauty and blooming identity, Flourish features a faceless silhouette adorned with vibrant hand-painted florals. Each petal is an expression of joy, each leaf a whisper of growth. Set against a calming sky-blue background, this piece evokes both peace and power.",
      "Flourish reminds us that home is where we grow into ourselves.",
    ],
    image: "/art/flourish.jpg",
    oldPath: "/store/p/flourish",
  },
  {
    slug: "its-my-time",
    wall: "teal",
    title: "It's My Time",
    price: 400,
    square: { code: "R1", itemId: "PX4GZOJTCEKOPA64P352F5SS", variationId: "63Z4RZZJ4SUTHUYV2ILWYJ6S" },
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    series: "Bloom",
    story: [
      "Floral patterns crown this faceless figure, with gold earrings and a necklace adding a subtle sense of elegance. Set against a rich pink background, It's My Time is about strength, softness, and growing into your full self.",
    ],
    image: "/art/its-my-time.jpg",
    oldPath: "/store/p/built-in-bloom",
  },
  {
    slug: "surviving-corporate-america",
    wall: "sky",
    title: "Surviving Corporate America",
    price: 200,
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    story: [
      "A bright yellow backdrop makes this portrait glow. Swirls of teal, orange, and purple move across the figure's face and chest, adding energy and rhythm to the piece.",
    ],
    image: "/art/surviving-corporate-america.jpg",
    oldPath: "/store/p/be-the-light",
  },
  {
    slug: "fully-seen",
    wall: "teal",
    title: "Fully Seen",
    price: 400,
    square: { code: "R2", itemId: "QQ6ADGLYEJLS5OCTIGBLYTPN", variationId: "OICSMFLXTF6RZNLOQMHBXFLB" },
    available: false,
    format: "canvas",
    size: '16" round',
    medium: "Acrylic on canvas",
    story: [
      "A faceless Black figure with long painted lashes, bold red lips, and a single flower over the heart, set against a bright orange background. Fully Seen is about presence. It's a reminder that you don't need to explain yourself to be powerful. You just need to show up.",
    ],
    image: "/art/fully-seen.jpg",
    oldPath: "/store/p/fully-seen",
  },
  {
    slug: "bright-and-grounded",
    wall: "pink",
    title: "Bright and Grounded",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A faceless figure in front of a vibrant, abstract background. Delicate blue and orange flowers grow from the chest. This piece blends boldness with calm, and is meant to bring color and care into small moments.",
    ],
    image: "/art/bright-and-grounded.jpg",
    oldPath: "/store/p/76watsn2q4p3lggyn1vz725kp1scuy",
  },
  {
    slug: "every-side-of-me",
    wall: "mustard",
    title: "Every Side of Me",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A colorful face split into bold shapes and sections. This card is about embracing every part of yourself: the loud, the quiet, the serious, the playful.",
    ],
    image: "/art/every-side-of-me.jpg",
    oldPath: "/store/p/every-side-of-me",
  },
  {
    slug: "layered-beauty",
    wall: "terracotta",
    title: "Layered Beauty",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Acrylic on paper",
    story: [
      "A floral-covered silhouette set against a layered, textured background. Made for anyone who finds power in their softness.",
    ],
    image: "/art/layered-beauty.jpg",
    oldPath: "/store/p/layered-beauty",
  },
  {
    slug: "family-unit",
    wall: "sky",
    title: "Family Unit",
    price: 30,
    available: false,
    format: "card",
    size: "5 x 7 in card",
    medium: "Watercolor on paper",
    story: [
      "A minimalist portrait of three faceless figures side by side. The simple shapes and soft tones reflect closeness, love, and identity within a family.",
    ],
    image: "/art/family-unit.jpg",
    oldPath: "/store/p/family-unit",
  },
];

export const available = () => artworks.filter((a) => a.available);
export const collected = () => artworks.filter((a) => !a.available);
export const bySlug = (slug: string) => artworks.find((a) => a.slug === slug);

export const formatPrice = (n: number) =>
  `$${n.toLocaleString("en-US", { maximumFractionDigits: 0 })}`;
